version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.17.18 # Use a stable 7.x version for simpler setup
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.17.18
    container_name: kibana
    ports:
      - 5601:5601 # Port for the web UI
    environment:
      # Point Kibana to the Elasticsearch service using its container name
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch # Start Kibana only after Elasticsearch is up

volumes:
  esdata: # Define the named volume for persistence
    driver: local