version: '3.8'

services:
  # PostgreSQL Database Service
  postgres-db:
    image: postgres:16-alpine # Using Alpine for a lighter footprint
    container_name: my_postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser        # CHANGE THIS
      POSTGRES_PASSWORD: mypassword # CHANGE THIS
      POSTGRES_DB: mydatabase      # CHANGE THIS
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data # Persist data even if container is deleted
    networks:
      - postgres-network

  # pgAdmin 4 Service (Web Interface)
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Login email for pgAdmin UI
      PGADMIN_DEFAULT_PASSWORD: root         # Login password for pgAdmin UI
    ports:
      - "5050:80" # Access pgAdmin at http://localhost:5050
    depends_on:
      - postgres-db
    networks:
      - postgres-network

volumes:
  pg_data: # Named volume for database persistence

networks:
  postgres-network:
    driver: bridge